`timescale 1ns / 1ps
// 仅供离线顶层连线检查，端口取自本地 DDR IP 包装器；不模拟板级 PLL/PHY。
module clk_pll(input clkin1, output clkout0, output lock);
endmodule
module GTP_INBUFGDS #(parameter IOSTANDARD="DEFAULT", parameter TERM_DIFF="ON")
    (output O, input I, input IB);
endmodule
module GTP_CFGCLK(input CLKIN, input CE_N);
endmodule
module GTP_INBUF #(parameter IOSTANDARD="DEFAULT", parameter TERM_DDR="ON")
    (output O, input I);
endmodule
module ddr3_ctrl_v116 #(
   parameter MEM_ROW_WIDTH       = 15          ,
   parameter MEM_COLUMN_WIDTH    = 10          ,
   parameter MEM_BANK_WIDTH      = 3           ,
  parameter MEM_DQ_WIDTH         =  32         ,
  parameter MEM_DM_WIDTH         =  4         ,
  parameter MEM_DQS_WIDTH        =  4         ,
  parameter CTRL_ADDR_WIDTH     = MEM_ROW_WIDTH + MEM_COLUMN_WIDTH + MEM_BANK_WIDTH ,
  parameter AXI_ADDR_SHIFT       = 2         ,
  parameter AXI_ADDR_WIDTH     = CTRL_ADDR_WIDTH + AXI_ADDR_SHIFT  ,
  parameter AXI_DATA_WIDTH     = 8*MEM_DQ_WIDTH  ,
  parameter DEVICE_ID            = 0
  )(
   input                              ref_clk                       ,
   input                              resetn                        ,
   output                             core_clk                      ,
   output                             pll_lock                      ,
   output                             phy_pll_lock                  ,
   output                             gpll_lock                     ,
   output                             rst_gpll_lock                 ,
   output                             ddrphy_cpd_lock               ,
   output                             ddr_init_done                 ,
   input [AXI_ADDR_WIDTH-1:0]         axi_awaddr                    ,
   input [7:0]                        axi_awid                      ,
   input [7:0]                        axi_awlen                     ,
   input [2:0]                        axi_awsize                    ,
   input [1:0]                        axi_awburst                   ,
   output                             axi_awready                   ,
   input                              axi_awvalid                   ,
   input [8*MEM_DQ_WIDTH-1:0]         axi_wdata                     ,
   input [MEM_DQ_WIDTH-1:0]           axi_wstrb                     ,
   input                              axi_wlast                     ,
   input                              axi_wvalid                    ,
   output                             axi_wready                    ,
   input                              axi_bready                    ,
   output [7:0]                       axi_bid                       ,
   output [1:0]                       axi_bresp                     ,
   output                             axi_bvalid                    ,
   input [AXI_ADDR_WIDTH-1:0]         axi_araddr                    ,
   input [7:0]                        axi_arid                      ,
   input [7:0]                        axi_arlen                     ,
   input [2:0]                        axi_arsize                    ,
   input [1:0]                        axi_arburst                   ,
   input                              axi_arvalid                   ,
   output                             axi_arready                   ,
   input                              axi_rready                    ,
   output [8*MEM_DQ_WIDTH-1:0]        axi_rdata                     ,
   output                             axi_rvalid                    ,
   output                             axi_rlast                     ,
   output [7:0]                       axi_rid                       ,
   output [1:0]                       axi_rresp                     ,
   input                              apb_clk                       ,
   input                              apb_rst_n                     ,
   input                              apb_sel                       ,
   input                              apb_enable                    ,
   input  [7:0]                       apb_addr                      ,
   input                              apb_write                     ,
   output                             apb_ready                     ,
   input  [15:0]                      apb_wdata                     ,
   output [15:0]                      apb_rdata                     ,
output                                mem_cs_n                      ,
   output                             mem_rst_n                     ,
   output                             mem_ck                        ,
   output                             mem_ck_n                      ,
   output                             mem_cke                       ,
   output                             mem_ras_n                     ,
   output                             mem_cas_n                     ,
   output                             mem_we_n                      ,
   output                             mem_odt                       ,
   output [MEM_ROW_WIDTH-1:0]         mem_a                         ,
   output [MEM_BANK_WIDTH-1:0]        mem_ba                        ,
   inout  [MEM_DQS_WIDTH-1:0]         mem_dqs                       ,
   inout  [MEM_DQS_WIDTH-1:0]         mem_dqs_n                     ,
   inout  [MEM_DQ_WIDTH-1:0]          mem_dq                        ,
   output [MEM_DM_WIDTH-1:0]          mem_dm                        ,
   input                              dbg_gate_start                ,
   input                              dbg_cpd_start                 ,
   input                              dbg_ddrphy_rst_n              ,
   input                              dbg_gpll_scan_rst             ,
   input                              samp_position_dyn_adj         ,
   input  [8*MEM_DQS_WIDTH-1:0]       init_samp_position_even       ,
   input                              wrcal_position_dyn_adj        ,
   input  [8*MEM_DQS_WIDTH-1:0]       init_wrcal_position           ,
   input                              force_read_clk_ctrl           ,
   input  [4*MEM_DQS_WIDTH-1:0]       init_slip_step                ,
   input  [3*MEM_DQS_WIDTH-1:0]       init_read_clk_ctrl            ,
   output [33:0]                      debug_calib_ctrl              ,
   output [4*MEM_DQS_WIDTH + 16:0]    dbg_slice_status              ,
   output [24*MEM_DQS_WIDTH -1:0]     dbg_slice_state               ,
   output [75*MEM_DQS_WIDTH -1:0]     debug_data                    ,
   output [1:0]                       dbg_dll_upd_state             ,
   output [8:0]                       debug_gpll_dps_phase          ,
   output [2:0]                       dbg_rst_dps_state             ,
   output [5:0]                       dbg_tran_err_rst_cnt          ,
   output                             dbg_ddrphy_init_fail          ,
   input                              debug_cpd_offset_adj          ,
   input                              debug_cpd_offset_dir          ,
   input  [9:0]                       debug_cpd_offset              ,
   output [9:0]                       debug_dps_cnt_dir0            ,
   output [9:0]                       debug_dps_cnt_dir1            ,
   input                              ck_dly_en                     ,
   input  [7:0]                       init_ck_dly_step              ,
   output [7:0]                       ck_dly_set_bin                ,
   output [8*8*MEM_DQS_WIDTH-1:0]     dq_idly_bin                   ,
   output [8*8*MEM_DQS_WIDTH-1:0]     dq_odly_bin                   ,
   output                             align_error                   ,
   output [3:0]                       debug_rst_state               ,
   output [3:0]                       debug_cpd_state
);
endmodule
