#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Fri Sep 11 21:46:10 2026

set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
synthesize -ads -selected_syn_tool_opt 2 
add_fic "F:/SocFpga/project/synthesize/Hfpga_soc_syn.fic"
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "F:/SocFpga/project/synthesize/Hfpga_soc_syn.fic"
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hnpu_dma
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hnpu_dma
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
add_design "F:/SocFpga/soc/flash_boot/flash_ddr_boot.v"
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L200H -speedgrade -6 -package FBB676
compile -top_module Hfpga_soc
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
