`ifndef CAMERA_REGS_VH
`define CAMERA_REGS_VH
// Compatibility names retained for existing RTL. Numeric values are owned by
// soc_addr_map.vh; include paths already make that file available to consumers.
`include "../soc/soc_addr_map.vh"
`define CAM_SNAPSHOT_CTRL        `SOC_CAM_SNAPSHOT_CTRL
`define CAM_FRAME_COUNT          `SOC_CAM_FRAME_COUNT
`define CAM_PIXEL_COUNT          `SOC_CAM_PIXEL_COUNT
`define CAM_PCLK_COUNT           `SOC_CAM_PCLK_COUNT
`define CAM_ERROR_FLAGS          `SOC_CAM_ERROR_FLAGS
`define CAM_LINE_COUNT           `SOC_CAM_LINE_COUNT
`define CAM_STATUS               `SOC_CAM_STATUS
`define CAM_BYTE_COUNT           `SOC_CAM_BYTE_COUNT
`define CAM_FIFO_LEVEL           `SOC_CAM_FIFO_LEVEL
`define CAM_FIFO_MAX_LEVEL       `SOC_CAM_FIFO_MAX_LEVEL
`define CAM_FIFO_ERROR           `SOC_CAM_FIFO_ERROR
`define CAM_DMA_STATUS           `SOC_CAM_DMA_STATUS
`define CAM_DMA_ERROR_CODE       `SOC_CAM_DMA_ERROR_CODE
`define CAM_LAST_FRAME_ADDR      `SOC_CAM_LAST_FRAME_ADDR
`define CAM_CURRENT_WRITE_BUFFER `SOC_CAM_CURRENT_WRITE_BUFFER
`define CAM_LAST_COMPLETE_BUFFER `SOC_CAM_LAST_COMPLETE_BUFFER
`define CAM_FRAME_CHECKSUM       `SOC_CAM_FRAME_CHECKSUM
`define CAM_READY_MASK           `SOC_CAM_READY_MASK
`define CAM_DROPPED_FRAMES       `SOC_CAM_DROPPED_FRAMES
`define CAM_SNAPSHOT_SEQUENCE    `SOC_CAM_SNAPSHOT_SEQUENCE
`define CAM_DVP_FRAME_COUNT      `SOC_CAM_DVP_FRAME_COUNT
`define CAM_DVP_ERROR_FLAGS      `SOC_CAM_DVP_ERROR_FLAGS
`define CAM_BUFFER_RELEASE       `SOC_CAM_BUFFER_RELEASE
`define CAM_DMA_CONTROL          `SOC_CAM_DMA_CONTROL
`define CAM_BUFFER0_ADDR         `SOC_CAM_BUFFER0_ADDR
`define CAM_BUFFER1_ADDR         `SOC_CAM_BUFFER1_ADDR
`define CAM_FRAME_BYTES          `SOC_CAM_FRAME_BYTES
`define CAM_FRAME_WIDTH          `SOC_CAM_FRAME_WIDTH
`define CAM_FRAME_HEIGHT         `SOC_CAM_FRAME_HEIGHT
`define CAM_DDR_READY            `SOC_CAM_DDR_READY
`define CAM_CURRENT_PIXEL_COUNT  `SOC_CAM_CURRENT_PIXEL_COUNT
`define CAM_CURRENT_BYTE_COUNT   `SOC_CAM_CURRENT_BYTE_COUNT
`define CAM_CURRENT_LINE_COUNT   `SOC_CAM_CURRENT_LINE_COUNT
`define CAM_ERR_NONE             `SOC_CAM_ERR_NONE
`define CAM_ERR_FIFO_OVERFLOW    `SOC_CAM_ERR_FIFO_OVERFLOW
`define CAM_ERR_UNEXPECTED_SOF   `SOC_CAM_ERR_UNEXPECTED_SOF
`define CAM_ERR_UNEXPECTED_EOF   `SOC_CAM_ERR_UNEXPECTED_EOF
`define CAM_ERR_BAD_PIXEL_COUNT  `SOC_CAM_ERR_BAD_PIXEL_COUNT
`define CAM_ERR_DDR_TIMEOUT      `SOC_CAM_ERR_DDR_TIMEOUT
`define CAM_ERR_DDR_WRITE        `SOC_CAM_ERR_DDR_WRITE
`define CAM_ERR_BAD_LINE_COUNT   `SOC_CAM_ERR_BAD_LINE_COUNT
`define CAM_ERR_DVP              `SOC_CAM_ERR_DVP
`define CAM_ERR_NO_FREE_BUFFER   `SOC_CAM_ERR_NO_FREE_BUFFER
`define CAM_ERR_BAD_CONFIG       `SOC_CAM_ERR_BAD_CONFIG
`define CAM_ERR_FIFO_UNDERFLOW   `SOC_CAM_ERR_FIFO_UNDERFLOW
`endif
